### ISSUE TITLE
Main monitoring program

### ISSUE THREAD

**Issue by pakozm** [ESAI-CEU-UCH/raspi-monitoring-system#1]
The main monitoring program would be a python script which should be executed this way:

```
$ python raspi_mon_system/MainMonitoringSystem.py
```

This program should use `raspi_mon_system.Scheduler` module in order to plan monitoring events. Basically it should do something like this:

```Python
import raspi_mon_system.Scheduler as Scheduler
import raspi_mon_system.AemetMonitor as Aemet
import raspi_mon_system.AnyModuleOtherModules as Whatever
...

T1_DECISECOND = 0.1
T1_SECOND = 1
T15_MINUTES = 60*15
T1_HOUR = 3600

# Configure Scheduler.
Scheduler.start()
Scheduler.repeat_o_clock(T15_MINUTES, Aemet.publish)
"""More calls to Scheduler for scheduling of other modules..."""

# Inifite loop.
Scheduler.loop_forever()

```

**EDIT** paho client has been removed because it could produce race conditions with Python threads.
Every module which needs connect to paho should use `Utils` module this way:

```Python
import raspi_mon_system.Utils as Utils
client = Utils.getpahoclient()
```

**Comment by PalomaBotellaRocamora** [comment]
Qué es esto Paco?

**Comment by pakozm** [comment]
Del proyecto de Miguel ;)

Pako ZM :)
http://pakozm.hol.es

On 30 October 2015 at 15:06, PalomaBotellaRocamora <notifications@github.com

**Comment by pakozm** [comment]
The implementation has been started scheduling `CheckIP.publish()` function for IP address checking.
